print('='*20)
print('Seja bem vindo{:=*^20}'.format(' '))
algo = input('Digite algo: ')
print('O tipo primitivo que você digitou é {}'.format(type(algo)))
print('Só tem espaços?{}'.format(algo.isspace()))
print('É um NÚMERO? {}'.format(algo.isnumeric()))
print('É ALFABETICO? {}'.format(algo.isalpha()))
print('É ALFANUMERICO? {}'.format(algo.isalnum()))
print('Está em maiúsculas? {}'.format(algo.isupper()))
print('Está em minúsculas?{}'.format(algo.islower()))
print('Está capitalizado?{}'.format(algo.istitle()))
